# Generated by Django 4.2.20 on 2025-04-22 13:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(default='no_image_kakml1', max_length=255, verbose_name='image'),
        ),
    ]
