# Generated by Django 4.2.20 on 2025-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=models.CharField(max_length=80),
        ),
    ]
