# Generated by Django 4.2.20 on 2025-04-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurb',
            field=models.CharField(default='A piece of crafting excellence', max_length=100),
        ),
    ]
