# Generated by Django 4.2.20 on 2025-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_post_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=models.CharField(default='A piece of crafting excellence', max_length=80),
        ),
    ]
