# Generated by Django 4.2.20 on 2025-04-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
